#!/bin/sh
# IncredibleLego

mkdir Day$1
cd Day$1

curl "https://adventofcode.com/2025/day/$1/input" \
	--compressed \
	-H "Cookie: session=$(cat ../../.aoc_cookie)" \
	> "input.txt"

touch day$1.go
echo "package main" > day$1.go
touch testfile
go mod init day$1
